## Deliverable 3. Create a Travel Itinerary Map.

In [1]:
# Dependencies and Setup
import pandas as pd
import requests
import gmaps

# Import API key
from config import g_key

# Configure gmaps
gmaps.configure(api_key=g_key)

In [2]:
# 1. Read the WeatherPy_vacation.csv into a DataFrame.
vacation_df = pd.read_csv("Vacation_Search/WeatherPy_vacation.csv")
vacation_df.head()

,City_ID,City,Country,Max Temp,Current Description,Lat,Lng,Hotel Name
0,2,Narsaq,GL,280.27,clear sky,60.9167,-46.0500,Narsaq Kayak Hostel
1,4,Busselton,AU,288.75,broken clouds,-33.6500,115.3333,Observatory Guest House
2,5,Diamantina,BR,284.78,broken clouds,-18.2494,-43.6003,POUSADA OURO DE MINAS
3,6,Hermanus,ZA,284.76,light rain,-34.4187,19.2345,Misty Waves Boutique Hotel
4,7,Richards Bay,ZA,288.63,clear sky,-28.7830,32.0377,BON Hotel Waterfront Richards Bay

In [3]:
# Drop any empty rows and create a new DataFrame that doesn’t have empty rows.
clean_hotel_df = vacation_df.dropna()
clean_hotel_df.head(20)

,City_ID,City,Country,Max Temp,Current Description,Lat,Lng,Hotel Name
0,2,Narsaq,GL,280.27,clear sky,60.9167,-46.0500,Narsaq Kayak Hostel
1,4,Busselton,AU,288.75,broken clouds,-33.6500,115.3333,Observatory Guest House
2,5,Diamantina,BR,284.78,broken clouds,-18.2494,-43.6003,POUSADA OURO DE MINAS
3,6,Hermanus,ZA,284.76,light rain,-34.4187,19.2345,Misty Waves Boutique Hotel
4,7,Richards Bay,ZA,288.63,clear sky,-28.7830,32.0377,BON Hotel Waterfront Richards Bay
5,12,Samfya,ZM,287.56,clear sky,-11.3649,29.5565,Chita Lodge Samfya
6,17,Nowe Miasto Lubawskie,PL,288.17,overcast clouds,53.4208,19.5952,Na Szlaku Smaku
7,19,Quelimane,MZ,287.12,few clouds,-17.8786,36.8883,Hotel Flamingo
8,23,Yuzhno-Kurilsk,RU,289.25,overcast clouds,44.0306,145.8556,Guesthouse Berloga
9,24,Port Alfred,ZA,287.29,scattered clouds,-33.5906,26.8910,The Halyards Hotel
10,28,Cidreira,BR,288.49,clear sky,-30.1811,-50.2056,Hotel Castelo
11,30,New Norfolk,AU,287.55,overcast clouds,-42.7826,147.0587,The Shingles Riverside Cottages
12,44,Narrabri,AU,289.54,overcast clouds,-30.3167,149.7833,Crossroads Hotel
13,59,Klaksvik,FO,282.66,overcast clouds,62.2266,-6.5890,Airbnb rooms
14,65,Cape Town,ZA,284.88,broken clouds,-33.9258,18.4232,Southern Sun Waterfront Cape Town
15,71,Hobart,AU,287.74,broken clouds,-42.8794,147.3294,Mantra on Collins Hobart
16,72,Tasiilaq,GL,282.24,light rain,65.6145,-37.6368,The Red House
17,75,Yellowknife,CA,280.91,broken clouds,62.4560,-114.3525,The Explorer Hotel
18,82,Taltal,CL,286.53,clear sky,-25.4000,-70.4833,Residencial Karime
19,83,Darovskoy,RU,289.02,light rain,58.7700,47.9564,"Hotel ""Central"""

In [89]:
# 2. Using the template add the city name, the country code, the weather description and maximum temperature for the city.
info_box_template = """
<dl>
<dt>City Name</dt><dd>{City}</dd>
<dt>Country</dt><dd>{Country}</dd>
<dt>Current Weather</dt><dd>{Current Description}</dd>
<dt>Max Temp</dt><dd>{Max Temp} °F</dd>
</dl>
"""

# 3a. Get the data from each row and add it to the formatting template and store the data in a list.
hotel_info = [info_box_template.format(**row) for index, row in clean_hotel_df.iterrows()]

# 3b. Get the latitude and longitude from each row and store in a new DataFrame.
locations = clean_hotel_df[["Lat", "Lng"]]

In [94]:
# 4a. Add a marker layer for each city to the map.
max_temp = clean_hotel_df["Max Temp"]
fig = gmaps.figure(center=(30.0, 31.0), zoom_level=1.5)
heat_layer = gmaps.heatmap_layer(locations, weights=max_temp,dissipating=False,
             max_intensity=300, point_radius=4)
marker_layer = gmaps.marker_layer(locations, info_box_content=hotel_info)
fig.add_layer(heat_layer)
fig.add_layer(marker_layer)

# 4b. Display the figure
fig

Figure(layout=FigureLayout(height='420px'))

In [98]:
# From the map above pick 4 cities and create a vacation itinerary route to travel between the four cities. 
# 5. Create DataFrames for each city by filtering the 'vacation_df' using the loc method. 
# Hint: The starting and ending city should be the same city.

vacation_start = vacation_df.loc[vacation_df['City']=='Lata']
vacation_end = vacation_df.loc [vacation_df['City']=='Lata']
vacation_stop1 = vacation_df.loc[vacation_df['City']=='Castanheira De Pera']
vacation_stop2 = vacation_df.loc[vacation_df['City']=='Areosa'] 
vacation_stop3 = vacation_df.loc[vacation_df['City']=='Aras']

In [99]:
# 6. Get the latitude-longitude pairs as tuples from each city DataFrame using the to_numpy function and list indexing.
start = vacation_start.iloc[0,5:7].to_numpy()
end = vacation_end.iloc[0,5:7].to_numpy()
stop1 = vacation_stop1.iloc[0,5:7].to_numpy()
stop2 = vacation_stop2.iloc[0,5:7].to_numpy()
stop3 = vacation_stop3.iloc[0,5:7].to_numpy()

print (start)
print (end)
print (stop1)
print (stop2)
print (stop3)

[40.1629 -8.3327]
[40.1629 -8.3327]
[40.0072 -8.2105]
[41.7178 -8.8571]
[42.5617 -2.356]

In [113]:
# 7. Create a direction layer map using the start and end latitude-longitude pairs,
# and stop1, stop2, and stop3 as the waypoints. The travel_mode should be "DRIVING", "BICYCLING", or "WALKING".
fig = gmaps.figure()
directions_layer_map = gmaps.directions_layer(
    start,end,waypoints=[stop1,stop2,stop3],
    travel_mode='DRIVING')

fig.add_layer(directions_layer_map)
fig

Figure(layout=FigureLayout(height='420px'))

In [114]:
# 8. To create a marker layer map between the four cities.
#  Combine the four city DataFrames into one DataFrame using the concat() function.
itinerary_df = pd.concat([vacation_start,vacation_stop1, 
                          vacation_stop2, vacation_stop3],ignore_index=True)
itinerary_df

,City_ID,City,Country,Max Temp,Current Description,Lat,Lng,Hotel Name
0,572,Lata,PT,284.85,broken clouds,40.1629,-8.3327,Casa Maquia
1,654,Castanheira De Pera,PT,286.03,scattered clouds,40.0072,-8.2105,Casa do Ouriço
2,384,Areosa,PT,289.99,overcast clouds,41.7178,-8.8571,Hotel Flôr de Sal
3,230,Aras,ES,287.63,scattered clouds,42.5617,-2.3560,Jardines de Viana Spa

In [116]:
# 9 Using the template add city name, the country code, the weather description and maximum temperature for the city. 
info_box_template = """
<dl>
<dt>Hotel Name</dt><dd>{Hotel Name}</dd>
<dt>City Name</dt><dd>{City}</dd>
<dt>Country</dt><dd>{Country}</dd>
<dt>Current Weather</dt><dd>{Current Description} and {Max Temp}</dd>
</dl>
"""

# 10a Get the data from each row and add it to the formatting template and store the data in a list.
hotel_info = [info_box_template.format(**row) for index, row in itinerary_df.iterrows()]

# 10b. Get the latitude and longitude from each row and store in a new DataFrame.
locations = itinerary_df[["Lat", "Lng"]]

In [118]:
# 11a. Add a marker layer for each city to the map.
marker_layer_map = gmaps.marker_layer(locations, info_box_content=hotel_info)
fig = gmaps.figure()
fig.add_layer(marker_layer_map)

# 11b. Display the figure
fig

Figure(layout=FigureLayout(height='420px'))